import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        tablet: '744px',
        desktop: '1280px',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        color: 'var(--color)',
        greyscale: {
          white: 'var(--greyscale-white)',
          100: 'var(--greyscale-100)',
          200: 'var(--greyscale-200)',
          300: 'var(--greyscale-300)',
          400: 'var(--greyscale-400)',
          500: 'var(--greyscale-500)',
          600: 'var(--greyscale-600)',
          700: 'var(--greyscale-700)',
          800: 'var(--greyscale-800)',
          900: 'var(--greyscale-900)',
        },
        bodyPrimary: 'var(--body-primary)',
        lightblue: {
          100: 'var(--lightblue-100)',
          200: 'var(--lightblue-200)',
          300: 'var(--lightblue-300)',
          400: 'var(--lightblue-400)',
          500: 'var(--lightblue-500)',
          600: 'var(--lightblue-600)',
          700: 'var(--lightblue-700)',
          800: 'var(--lightblue-800)',
          900: 'var(--lightblue-900)',
        },
        lightyellow: {
          100: 'var(--lightyellow-100)',
          200: 'var(--lightyellow-200)',
          300: 'var(--lightyellow-300)',
          400: 'var(--lightyellow-400)',
          500: 'var(--lightyellow-500)',
          600: 'var(--lightyellow-600)',
          700: 'var(--lightyellow-700)',
          800: 'var(--lightyellow-800)',
          900: 'var(--lightyellow-900)',
        },
        lightgreen: {
          100: 'var(--lightgreen-100)',
          200: 'var(--lightgreen-200)',
          300: 'var(--lightgreen-300)',
          400: 'var(--lightgreen-400)',
          500: 'var(--lightgreen-500)',
          600: 'var(--lightgreen-600)',
          700: 'var(--lightgreen-700)',
          800: 'var(--lightgreen-800)',
          900: 'var(--lightgreen-900)',
        },
        orange: {
          100: 'var(--orange-100)',
          200: 'var(--orange-200)',
          300: 'var(--orange-300)',
          400: 'var(--orange-400)',
          500: 'var(--orange-500)',
          600: 'var(--orange-600)',
          700: 'var(--orange-700)',
          800: 'var(--orange-800)',
          900: 'var(--orange-900)',
        },
        pink: {
          100: 'var(--pink-100)',
          200: 'var(--pink-200)',
          300: 'var(--pink-300)',
          400: 'var(--pink-400)',
          500: 'var(--pink-500)',
          600: 'var(--pink-600)',
          700: 'var(--pink-700)',
          800: 'var(--pink-800)',
          900: 'var(--pink-900)',
        },
        fillwhite: {
          4: 'var(--fill-white-4)',
          10: 'var(--fill-white-10)',
          20: 'var(--fill-white-20)',
          40: 'var(--fill-white-40)',
          60: 'var(--fill-white-60)',
          80: 'var(--fill-white-80)',
        },
        fillblack: {
          10: 'var(--fill-black-10)',
          20: 'var(--fill-black-20)',
          80: 'var(--fill-black-80)',
        },
      },
      typography: {
        DEFAULT: {
          css: {
            blockquote: {
              fontFamily: "'Noto Serif KR', serif",
            },
            h1: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '48px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '0',
              paddingBottom: '1.5em',
              color: 'var(--greyscale-900)',
            },
            h2: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '48px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '8px',
              paddingBottom: '40px',
              color: 'var(--greyscale-white)',
            },
            h3: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '38px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '1.6em',
              paddingBottom: '0.8em',
              color: 'var(--greyscale-white)',
            },
            h4: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '28px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '1.5em',
              paddingBottom: '0.5em',
              color: 'var(--greyscale-white)',
            },
            h5: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '28px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '1.25em',
              paddingBottom: '0.5em',
              color: 'var(--greyscale-white)',
            },
            h6: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '14px',
              fontWeight: '500',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '8px',
              paddingBottom: '24px',
              color: 'var(--greyscale-white)',
            },
          },
        },
        lg: {
          css: {
            blockquote: {
              fontFamily: "'Noto Serif KR', serif",
            },
            h1: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '48px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '0',
              paddingBottom: '1.5em',
              color: 'var(--greyscale-900)',
            },
            h2: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '48px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '8px',
              paddingBottom: '40px',
              color: 'var(--greyscale-white)',
            },
            h3: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '38px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '1.6em',
              paddingBottom: '0.8em',
              color: 'var(--greyscale-white)',
            },
            h4: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '28px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '1.5em',
              paddingBottom: '0.5em',
              color: 'var(--greyscale-white)',
            },
            h5: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '28px',
              fontWeight: '700',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '1.25em',
              paddingBottom: '0.5em',
              color: 'var(--greyscale-white)',
            },
            h6: {
              fontFamily: "'Noto Serif KR', serif",
              fontSize: '14px',
              fontWeight: '500',
              lineHeight: '1.4',
              letterSpacing: '0',
              paddingTop: '8px',
              paddingBottom: '24px',
              color: 'var(--greyscale-white)',
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
export default config

